
	.NEW			; NEW ZIP INTERPRETER
	.INSERT "TRFREQ"        ; FWORDS TABLE
	.INSERT "TRDAT"
	.INSERT "SYNTAX"
	.INSERT "MISC"
	.INSERT "PARSER"
	.INSERT "VERBS"
	.INSERT "EVENTS"
	.INSERT "PEOPLE"
	.INSERT "PLACES"
	.INSERT "THINGS"
	.INSERT "TRSTR"
	.END
